[package]
name = "timetracker-core"
version = "0.1.0"
authors = ["Samuli Suortti <smulis@aiven.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
unix_socket = "0.5.0"
dbus = "0.9.1"
